_schema: _schema
# Point CloudCannon to the static output folder created by Eleventy.
# After building with `npm run build`, Eleventy will create `_site/index.html`
# from `src/index.njk` and CloudCannon should serve that.
source: _site
paths:
  uploads: uploads
  static: ""
timezone: Europe/Bucharest
markdown:
  engine: commonmark
  options:
    html: true
# If you prefer CloudCannon to edit source files directly, set `source: src`.
# For static deployments using Eleventy, `source: _site` is appropriate.
